### ISSUE TITLE
The default page should be index not styleguide

### ISSUE THREAD

**Issue by iamtomnewton** [code-computerlove/node-static-site-generator#38]
It's a small thing to go in and change each time but it seems silly to have to change it in routes/styleguide.js when like 99% of the time you're going to use this to make a site...

**Comment by andrewbrandwood** [comment]
I originally did this on purpose to encourage starting with a styleguide.  Having since used it on several projects, it is beginning to bug me too. :)

We are looking to build a module further down the line to auto generate a styleguide as an option. Happy to change in the interim. 

Worth a discussion for sure.

**Comment by tawashley** [comment]
It lower the barrier of entry, for sure, if only by removing one small thing to get up and running. I'll go about and remove it, it's easy enough to add it back in

**Comment by furzeface** [comment]
No objections, anything that makes it even slightly less painful and quicker to use is a good thing!

**Comment by furzeface** [comment]
Resolved with PR #39
